import Head from "next/head";
import Hero from "../components/Hero";
import Invite from "../components/Invite";
import Card from "../components/Card";
import Roadmap from "../components/Roadmap";
import FrequentlyAskedQuestions from "../components/FrequentlyAskedQuestions";
import ContactForm from "../components/ContactForm";
import Subscribe from "../components/Subscribe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        title="Experience the Power of Digital Business Profiles!"
        text="And discover the added perks."
      />
      <Invite
        path="/"
        title="Create your personal or business profile in less than two minutes."
        text="Create a profile for free and start enjoying a range of benefits! Our platform provides a social network exclusively for users, giving you the opportunity to connect with like-minded professionals end expand your network. You will also be able to access exclusive discounts on selected products."
        btnTxt="Get started for free"
        width={868}
        height={580}
      />
      <Card text="Get an NFC card and link it to your profile. We plant a tree for each card!" />
      <Invite
        path="/"
        title="Experience effortless team management."
        text="Make managing your team easier than ever with one dashboard - all in one place!
Discover our white label CRM system for teams and companies that includes powerful statistics and social network capabilities. Customize features to fit the specific needs of your team. This offers the flexibility and convenience of a powerful CRM system without having to build it from scratch."
        btnTxt="Get started"
        width={1024}
        height={615}
      />
      <Invite
        path="/"
        title="Get up to 70% discount on selected products."
        text="Register now and take advantage of numerous discounted products. By signing up, you'll have access to exclusive offers and be able to earn points by purchasing products or simply by being an active member. Unlock even better deals when you reach higher loyalty levels and enjoy the rewards of being a valued customer."
        btnTxt="Get started for free"
        width={234}
        height={314}
      />
      <Invite
        path="/"
        title="Over 2M hotels worldwide, up to 70% off!"
        text="Take advantage of GPM.Travel now and get up to 70% off for your next stay. With an extensive selection of more than 2M hotels and resorts around the world, you'll be able to find the ideal destination for your next holiday! Register now and start making the most of your vacation with GPM.Travel!"
        btnTxt="Get started for free"
        width={477}
        height={259}
      />
      <Invite
        path="/"
        title="Go further - get an NFT that gives you up to 300% per year!"
        text="Discover our NFT collection designed to provide up to 1000% return on your investment annually. With NFTs, you can experience true ownership of digital assets and have the opportunity to maximize your profits with referrals. Have some fun and laverage on the potential of NFTs!"
        btnTxt="Learn more"
        width={368}
        height={231}
      />
      <Invite
        path="/"
        title="Become a reseller and start earning now."
        text="Become a GPM.Team reseller by launching your own branded Digital Business Card Platform for Businesses & Teams in days and start earning up to 65% on your customers' subscriptions and up to 35% on customers' product purchases."
        btnTxt="Learn more"
        width={588}
        height={285}
      />
      <Roadmap />
      <FrequentlyAskedQuestions />
      <ContactForm />
      <Subscribe />
    </>
  );
}
